//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wxBIZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wxEntities : DbContext
    {
        public wxEntities()
            : base("name=wxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_logs> T_logs { get; set; }
        public DbSet<T_Access_Token> T_Access_Token { get; set; }
        public DbSet<T_Setting> T_Setting { get; set; }
        public DbSet<T_SysLogs> T_SysLogs { get; set; }
        public DbSet<T_ImgMessage> T_ImgMessage { get; set; }
        public DbSet<T_TextMessage> T_TextMessage { get; set; }
    }
}
